#!/bin/bash

#  This is source code for "accepttest", a script for accepting the new
#  result of a unit test.  It is a part of a very simple framowork for unit
#  and functional tests.
# 
#  Copyright 2014 Andrey Vladimirovich Sobol, andrey.v.sobol@gmail.com
#  
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

rm -rf $1/good
cp -r $1/current $1/good
