#!/bin/bash

#  This is source code for "runtests", a script for running a unit test.
#  It is a part of a very simple framowork for unit and functional tests.
# 
#  Copyright 2014 Andrey Vladimirovich Sobol, andrey.v.sobol@gmail.com
#  
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

L=`ls tests`

for F in $L ; do
   pushd tests/$F 1> /dev/null 2<&1
      rm -rf current
      cp -r input current
      cd current
      ./run
      cd ..
      diff -r good current 1> log 2<&1
      result=$?
      echo -n $F
      if [ $result -eq 0 ] ; then
         echo '  +'
      else
         echo '  -'
      fi
   popd 1> /dev/null 2<&1
done
